### ISSUE TITLE
Не работают тесты

### ISSUE THREAD

**Issue by hram** [ukakhmedoff/Hieronymus#1]
Если в ApiInterfaceTest закоментировать MockWebServer server то тесты все равно пройдут
Тесты работают напрямую с сервером без использования ответов langs.json и translate.json

Казалось бы вот оно самое место дагеру, но почему то его тут нет.
Не подскажите как починить тесты чтоб они стали работать через MockWebServer ?

**Comment by ukakhmedoff** [comment]
Нам нужно получить ссылку на server с помощью HttpUrl, после чего отправляем ее в getApiInterfaceInstance(), в котором мы проставляем ссылку в Retrofit

**Comment by hram** [comment]
Если это не сделано в чем смысл тогда использования MockWebServer ?

**Comment by ukakhmedoff** [comment]
Сейчас исправлю.

**Comment by ukakhmedoff** [comment]
И спасибо)
